{ config, lib, pkgs, ... }:

{
  # nvim-based pager that isn't annoying: renders ANSI colors, passes short
  # output straight through (cat mode), quits on q.
  home.packages = [ pkgs.nvimpager ];

  home.sessionVariables = {
    PAGER = "nvimpager";
    MANPAGER = "nvim +Man!"; # man pages as proper nvim buffers
  };

  programs.neovim = {
    enable = true;
    defaultEditor = true; # sets $EDITOR = nvim

    extraPackages = with pkgs; [ ripgrep fd ];

    # Inlined into the generated ~/.config/nvim/init.lua; the lua/ and after/
    # trees it requires are linked below.
    initLua = builtins.readFile ../config/nvim/init.lua;

    plugins = with pkgs.vimPlugins; [
      # shared dependencies
      plenary-nvim
      nvim-web-devicons
      nui-nvim

      # util
      git-blame-nvim
      undotree
      trim-nvim

      # lsp
      none-ls-nvim
      lspkind-nvim
      nvim-lightbulb

      # completion
      nvim-cmp
      cmp-buffer
      cmp-cmdline
      cmp-nvim-lsp
      cmp-nvim-lua
      cmp-path
      cmp_luasnip
      friendly-snippets
      luasnip

      # syntax / treesitter (precompiled grammars, no runtime install)
      nvim-treesitter.withAllGrammars
      rainbow-delimiters-nvim
      todo-comments-nvim

      # rust
      rustaceanvim
      crates-nvim

      # ui
      nord-nvim
      telescope-nvim
      tokyonight-nvim
      lualine-nvim
      lsp-status-nvim
      neo-tree-nvim
      aerial-nvim
      gitsigns-nvim

      # colors
      base16-nvim

      # obsidian
      obsidian-nvim
    ];
  };

  # init.lua is generated by programs.neovim; only the module trees are linked.
  xdg.configFile."nvim/lua".source = ../config/nvim/lua;
  xdg.configFile."nvim/after".source = ../config/nvim/after;
}
