# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# Hyprlock

background {
    monitor =
    path = $HOME/.local/share/backgrounds/wallhaven-l8lzpq_3840x1600.png

    blur_size = 5
    blur_passes = 1
    noise = 0.0117
    contrast = 1.3000
    brightness = 0.8000
    vibrancy = 0.2100
    vibrancy_darkness = 0.0
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 3
    dots_size = 0.33
    dots_spacing = 0.15
    dots_center = true
    outer_color = rgb(082a72)
    inner_color = rgb(1a1b26)
    font_color = rgb(91b4ff)
    placeholder_text = <i>Password...</i>
    hide_input = false

    position = 0, 200
    halign = center
    valign = bottom
}

# Date
label {
    monitor =
    text = cmd[update:18000000] echo "<b> "$(date +'%A, %-d %B %Y')" </b>"
    color = rgb(91b4ff)
    font_size = 34
    font_family = JetBrains Mono Nerd Font 10

    position = 0, -150
    halign = center
    valign = top
}

# Week
label {
    monitor =
    text = cmd[update:18000000] echo "<b> "$(date +'Week %U')" </b>"
    color = rgb(082a72)
    font_size = 24
    font_family = JetBrains Mono Nerd Font 10

    position = 0, -250
    halign = center
    valign = top
}

# Time
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%H:%M:%S") </big></b>"
    color = rgb(f8faff)
    font_size = 94
    font_family = JetBrains Mono Nerd Font 10

    position = 0, 0
    halign = center
    valign = center
}

# User
label {
    monitor =
    text =    $USER
    color = rgb(91b4ff)
    font_size = 18
    font_family = Inter Display Medium

    position = 0, 100
    halign = center
    valign = bottom
}
