preload = ~/.local/share/backgrounds/antarctica-huge.png
preload = ~/.local/share/backgrounds/wallhaven-l8lzpq_3840x1600.png
wallpaper = DP-1,~/.local/share/backgrounds/wallhaven-l8lzpq_3840x1600.png
