-- Auto-generated by DMS - do not edit manually

hl.monitor({
    output   = "desc:Dell Inc. DELL U4025QW 81B3934",
    mode     = "5120x2160@120.000",
    position = "0x0",
    scale    = 0.80078125,
    vrr      = 1,
    bitdepth = 10,
})

-- Fallback entry for the same monitor description at scale 1.0
hl.monitor({
    output   = "desc:Dell Inc. DELL U4025QW 81B3934",
    mode     = "5120x2160@120.000",
    position = "0x0",
    scale    = 1,
    vrr      = 1,
    bitdepth = 10,
})

-- (removed) DP-1 was disabled on the old Arch box; on intrepid the Dell is DP-1
